- OG_data:
    bckup: 1561723022_sdp_l0.full_1284.full_pol_split_1024ch_3C274_64_chn_32s.ms

- Duplicates:
    mslist: auto1,auto2,auto3

- UV_range:
    uvrange: nill,nill,nill

- Masking:
    mask_list: nill,nill,nill

- Wsclean_range:
    min_range:  nill,nill,nill

- BDSM:
    bdsf_par: nill;nill,nill;nill,nill;nill

- Imaging:
    robustness: -2.0,-2.0,-2.0
    auto_threshold: 3,3,3
    automatic_mask_size: 5,5,5
    multiscale_clean: True,True,True
    multiscale_scales: 10;20;30,10;20;30,10;20;30
    taper_UV: nill,nill,nill
    uv_tapering: 2.0,2.0,2.0

- Selfcal:
    data-column          : "DATA"               ### Column in which the data lives.
    out-column           : "CORRECTED_DATA"
    weight-column        : "WEIGHT_SPECTRUM"
    model-ddes           : "auto"
    g-solvable           : True
    g-type               : "f-slope"           ### Solves for residual delays + phase ###
    sol-jones            : "G"
    sol-min-bl           : 300
    g-clip-high          : 2.5
    g-clip-low           : 0.5
    g-solvable           : True
    g-time-int           : 15    ### solution interval of 15 timeslots - should be really 1 timeslot for delays ###
    g-freq-int           : 0     ### solution interval in f: the whole bandwidth, i.e. don't solve for bandpass ###
    model-list           : spf("MODEL_DATA")
    sol-term-iters       : 30
    out-name             : "delayself_0"
    data-freq-chunk      : 0
    data-time-chunk      : 1
    out-mode             : "sc"
    madmax-threshold     : [10,12]
    log-verbose          : 'solver=2'
    #g_save_to            : "phase-0-{0:d}.parmdb".format(i)
    

- EMAIL:
    address: 13371062@tuks.co.za

#----------------------------------------------------------------------------
#----------------------------------------------------------------------------
## The purpose of this experience is to test the effectiveness of:
#
## On the conclusion of this job I expect to comment on:
#
## The importance of leaving the state of the parameter as
# active/disabled
## For the following reason:
#
#----------------------------------------------------------------------------
