- OG_data:
    bckup: 8sec_ch3_ch7_removed_lo.ms

- Duplicates:
    mslist: auto1,auto2,auto3

- UV_range:
    uvrange: nill,nill,nill

- Masking:
    mask_list: nill,nill,nill

- Wsclean_range:
    min_range:  nill,nill,nill

- BDSM:
    bdsf_par: nill;nill,nill;nill,nill;nill

- Imaging:
    robustness: -2.0,-2.0,-2.0
    auto_threshold: 3,3,3
    automatic_mask_size: 5,5,5
    multiscale_clean: True,True,True
    multiscale_scales: 10;20;30,10;20;30,10;20;30
    taper_UV: nill,nill,nill
    uv_tapering: 2.0,2.0,2.0

- Selfcal:
    data-column: DATA,DATA,DATA           ### Column in which the data lives.
    out-column: CORRECTED_DATA,CORRECTED_DATA,CORRECTED_DATA
    weight-column: WEIGHT_SPECTRUM,WEIGHT_SPECTRUM,WEIGHT_SPECTRUM
    model-ddes: auto,auto,auto
    g-solvable: True,True,True
    g-type: f-slope,f-slope,f-slope           ### Solves for residual delays + phase ###
    sol-jones: G,G,G
    sol-min-bl: 300,300,300
    g-clip-high: 2.5,2.5,2.5
    g-clip-low: 0.5,0.5,0.5
    g-solvable: True,True,True
    g-time-int: 15,15,15    ### solution interval of 15 timeslots - should be really 1 timeslot for delays ###
    g-freq-int: 0,0,0     ### solution interval in f: the whole bandwidth, i.e. don't solve for bandpass ###
    model-list: MODEL_DATA,MODEL_DATA,MODEL_DATA
    sol-term-iters: 30,30,30
    out-name: delayself_0,delayself_1,delayself_2
    data-freq-chunk: 0,0,0
    data-time-chunk: 1,1,1
    out-mode: sc,sc,sc
    madmax-threshold: 10;12,10;12,10;12
    log-verbose: solver=2,solver=2,solver=2
    g_save_to: phase-0-0.parmdb,phase-1-1.parmdb,phase-2-2.parmdb
  
- OG_data_path:
    path: /scratch3/users/mtshweni/oxkat_2.0/testing_multi_image/

- EMAIL:
    address: u13371062@tuks.co.za

#----------------------------------------------------------------------------
#----------------------------------------------------------------------------
## The purpose of this experience is to test the effectiveness of:
#
## On the conclusion of this job I expect to comment on:
#
## The importance of leaving the state of the parameter as
# active/disabled
## For the following reason:
#
